services:
  db:
    image: postgres:14.4-alpine
    env_file:
      - .env.local
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # not needed but convenient for running django in true local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
  migration:
    build: .
    command: python src/manage.py migrate
    env_file:
      - .env.local
    depends_on:
      - django
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  elasticsearch-index:
    build: .
    command: python src/manage.py search_index --rebuild -f
    env_file:
      - .env.local
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  postgres_data: