name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        make docker/build
    - name: Forgotten migrations
      run: |
        make docker/migrations/check
    - name: Lint
      run: |
        make docker/format/check
    - name: Unit tests
      run: |
        make docker/tests